spring:
  application:
    name: author-service
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:author-db;database_to_upper=true

jimmer:
  language: kotlin
  micro-service-name: ${spring.application.name}
  show-sql: true
  executor-context-prefixes:
    - org.babyfish.jimmer.example.cloud.kt.author.AuthorService
  database-validation-mode: ERROR
  client:
    ts:
      path: /author-service-ts.zip

server:
  port: 7003

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7000/eureka/

springdoc:
  swagger-ui:
    path: /ui