spring:
  graphql:
    graphiql:
      enabled: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:jimmer-sql-graphql-kt;database_to_upper=true

jimmer:
  language: kotlin
  dialect: org.babyfish.jimmer.sql.dialect.H2Dialect
  database-validation-mode: ERROR
  show-sql: true
  pretty-sql: true
  
demo:
  default-tenant: a