[versions]
antlr = "4.13.0"
buildconfig = "5.3.5"
caffeine = "2.9.1"
redisson = "3.32.0"
h2 = "2.1.212"
intellijAnnotations = "12.0"
jackson = "2.15.2"
jackson3 = "3.0.3"
jakartaValidation = "2.0.2"
jakartaee = "9.0.0"
javapoet = "1.13.0"
javaxValidation = "2.0.1.Final"
jetbrainsAnnotations = "24.0.0"
jspecify = "1.0.0"
kafka = "0.10.0.0"
kotlinpoet = "2.2.0"
ksp = "2.1.20-2.0.0"
lombok = "1.18.38"
mapstruct = "1.5.3.Final"
mysql = "8.0.29"
postgresql = "42.3.6"
sqlite = "3.47.0.0"
slf4j = "1.7.36"
spring = "5.3.20"
springBoot = "2.7.0"
springGraphql = "1.0.0"
springdoc = "1.7.0"
hibernateValitation = "8.0.1.Final"
quarkus = "3.15.0"

[libraries]
antlr = { group = "org.antlr", name = "antlr4", version.ref = "antlr" }

caffeine = { group = "com.github.ben-manes.caffeine", name = "caffeine", version.ref = "caffeine" }
redisson = { group = "org.redisson", name = "redisson", version.ref = "redisson" }
redisson-spring-boot-starter = { group = "org.redisson", name = "redisson-spring-boot-starter", version.ref = "redisson" }

h2 = { group = "com.h2database", name = "h2", version.ref = "h2" }

intellij-annotations = { group = "com.intellij", name = "annotations", version.ref = "intellijAnnotations" }

jackson-databind = { group = "com.fasterxml.jackson.core", name = "jackson-databind", version.ref = "jackson" }
jackson-datatype-jsr310 = { group = "com.fasterxml.jackson.datatype", name = "jackson-datatype-jsr310", version.ref = "jackson" }
jackson-module-kotlin = { group = "com.fasterxml.jackson.module", name = "jackson-module-kotlin", version.ref = "jackson" }
jackson3-core = { group = "tools.jackson.core", name = "jackson-core", version.ref = "jackson3" }
jackson3-databind = { group = "tools.jackson.core", name = "jackson-databind", version.ref = "jackson3" }

jakarta-validation-api = { group = "jakarta.validation", name = "jakarta.validation-api", version.ref = "jakartaValidation" }
jakartaee-api = { group = "jakarta.platform", name = "jakarta.jakartaee-api", version.ref = "jakartaee" }

javapoet = { group = "com.squareup", name = "javapoet", version.ref = "javapoet" }

javax-validation-api = { group = "javax.validation", name = "validation-api", version.ref = "javaxValidation" }

jetbrains-annotations = { group = "org.jetbrains", name = "annotations", version.ref = "jetbrainsAnnotations" }
jspecify = { group = "org.jspecify", name = "jspecify", version.ref = "jspecify" }

kafka-connect-api = { group = "org.apache.kafka", name = "connect-api", version.ref = "kafka" }

kotlin-reflect = { group = "org.jetbrains.kotlin", name = "kotlin-reflect" }
kotlin-stdlib = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib" }
kotlin-test = { group = "org.jetbrains.kotlin", name = "kotlin-test" }

kotlinpoet = { group = "com.squareup", name = "kotlinpoet", version.ref = "kotlinpoet" }
kotlinpoet-ksp = { group = "com.squareup", name = "kotlinpoet-ksp", version.ref = "kotlinpoet" }

ksp-symbolProcessing-api = { group = "com.google.devtools.ksp", name = "symbol-processing-api", version.ref = "ksp" }

lombok = { group = "org.projectlombok", name = "lombok", version.ref = "lombok" }

mapstruct = { group = "org.mapstruct", name = "mapstruct", version.ref = "mapstruct" }
mapstruct-processor = { group = "org.mapstruct", name = "mapstruct-processor", version.ref = "mapstruct" }

mysql-connector-java = { group = "mysql", name = "mysql-connector-java", version.ref = "mysql" }

postgresql = { group = "org.postgresql", name = "postgresql", version.ref = "postgresql" }

sqlite = { group = "org.xerial", name = "sqlite-jdbc", version.ref = "sqlite" }

slf4j-api = { group = "org.slf4j", name = "slf4j-api", version.ref = "slf4j" }

spring-core = { group = "org.springframework", name = "spring-core", version.ref = "spring" }
spring-jdbc = { group = "org.springframework", name = "spring-jdbc", version.ref = "spring" }
spring-web = { group = "org.springframework", name = "spring-web", version.ref = "spring" }

spring-boot = { group = "org.springframework.boot", name = "spring-boot", version.ref = "springBoot" }
spring-boot-configurationProcessor = { group = "org.springframework.boot", name = "spring-boot-configuration-processor", version.ref = "springBoot" }
spring-boot-starter-jdbc = { group = "org.springframework.boot", name = "spring-boot-starter-jdbc", version.ref = "springBoot" }
spring-boot-starter-web = { group = "org.springframework.boot", name = "spring-boot-starter-web", version.ref = "springBoot" }
spring-boot-starter-test = { group = "org.springframework.boot", name = "spring-boot-starter-test", version.ref = "springBoot" }

spring-data-commons = { group = "org.springframework.data", name = "spring-data-commons", version.ref = "springBoot" }
spring-data-redis = { group = "org.springframework.data", name = "spring-data-redis", version.ref = "springBoot" }

spring-graphql = { group = "org.springframework.graphql", name = "spring-graphql", version.ref = "springGraphql" }

springdoc-openapi-common = { group = "org.springdoc", name = "springdoc-openapi-common", version.ref = "springdoc" }

quarkus-redis-client = { group = "io.quarkus", name = "quarkus-redis-client", version.ref = "quarkus" }

hibernate-validation = { group = "org.hibernate", name = "hibernate-validator", version.ref = "hibernateValitation" }

[plugins]
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
buildconfig = { id = "com.github.gmazzo.buildconfig", version.ref = "buildconfig" }