spring:
  graphql:
    graphiql:
      enabled: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:jimmer-sql-graphql;database_to_upper=true

jimmer:
  dialect: org.babyfish.jimmer.sql.dialect.H2Dialect
  id-only-target-checking-level: ALL
  database-validation-mode: ERROR
  show-sql: true
  pretty-sql: true

  # You can enable the following configuration line `inline-sql-variables: true`,
  # restart the application and call some REST APIs again to see what happens
  # inline-sql-variables: true

  executor-context-prefixes:
    - org.babyfish.jimmer.sql.example.graphql.business

demo:
  default-tenant: a