spring:
  application:
    name: book-service
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:book-db;database_to_upper=true

jimmer:
  micro-service-name: ${spring.application.name}
  show-sql: true
  pretty-sql: true
  executor-context-prefixes:
    - org.babyfish.jimmer.example.cloud.book.BookService
  database-validation-mode: ERROR
  client:
    ts:
      path: /book-service-ts.zip

server:
  port: 7002

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7000/eureka/

springdoc:
  swagger-ui:
    path: /ui