spring:
  application:
    name: store-service
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:store-db;database_to_upper=true

jimmer:
  language: kotlin
  micro-service-name: ${spring.application.name}
  show-sql: true
  pretty-sql: true
  executor-context-prefixes:
    - org.babyfish.jimmer.example.cloud.kt.store.StoreService
  database-validation-mode: ERROR
  client:
    ts:
      path: /store-service-ts.zip
    openapi:
      path: /open-api.yml
      ui-path: /open-api.html

server:
  port: 7001

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7000/eureka/
